#! /bin/bash
#docker network create --subnet=192.168.0.0/16 multi-user-net
#docker run --userns=host --net multi-user-net --ip 192.168.0.157  -p 80:80 -v $PWD:/usr/src/app -w /usr/src/app -v ~/.minikube/:/.minikube/:ro -it node:6 bash
#On local-machine;  To be run from the folder where nodejs code is present

#redis
docker run --name redis-db -d -p 6390:6379 redis:3.2
#MongoDB
docker run --name filemanager-mongo -p 27017:27017 --restart=unless-stopped -d mongo

docker run -p 80:80  --name=node-manager --env PORT=80 --env NODE_ENV=production -v $PWD:/usr/src/app -w /usr/src/app -d node:6 bash -c "npm install && npm start -- watcher webserver apiserver"

#to use the jupyter image
docker run -p 80:80  --name=node-manager --env PORT=80 --env NODE_ENV=production -v $PWD:/usr/src/app -w /usr/src/app -d node:6 bash -c "npm install && npm start -- --image-type jupyter watcher webserver apiserver"

#On labdev-nomad ;  To be run from the folder where nodejs code is present

docker run -p 8801:443 --restart=unless-stopped  --name=beaker-manager-https --env PORT=443 --env NODE_ENV=labdev -v /u/ankar/certi:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- webserver"
docker run -p 880:443 --restart=unless-stopped  --name=beaker-manager-api --env PORT=443 --env NODE_ENV=labdev -v /u/ankar/certi:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- apiserver"
docker run --restart=unless-stopped  --name=beaker-manager-watcher --env PORT=443 --env NODE_ENV=labdev -v /u/ankar/certi:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- watcher"
# jupyter:
docker run -p 8807:443 --restart=unless-stopped  --name=jupyter-manager-https --env PORT=443 --env NODE_ENV=labdev -v /u/ankar/certi:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- --image-type jupyter webserver"

# remote-vis:
docker run -p 8807:443 --restart=unless-stopped  --name=remote-vis-manager-https --env PORT=443 --env NODE_ENV=labdev -v /u/ankar/certi:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- --image-type remotevis webserver"

#On analytics-toolkit or labtest-nomad; To be run from the folder where nodejs code is present

docker run -p 8801:443  --restart=unless-stopped --name=beaker-manager-https --env PORT=443 --env NODE_ENV=analyticsToolkit -v /root/nomad-coe:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- webserver"
docker run -p 8802:443  --restart=unless-stopped --beaker-manager-api --env PORT=443 --env NODE_ENV=analyticsToolkit -v /root/nomad-coe:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- apiserver"
docker run --restart=unless-stopped --name=beaker-manager-watcher --env PORT=443 --env NODE_ENV=analyticsToolkit -v /root/nomad-coe:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- watcher"
#jupyter labtest
docker run -p 8807:443  --restart=unless-stopped --name=jupyter-manager-https --env PORT=443 --env NODE_ENV=analyticsToolkit -v /root/nomad-coe:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- --image-type jupyter webserver"
#creedo on analytics toolkit
docker run -p 8805:443  --restart=unless-stopped --name=creedo-manager --env PORT=443 --env NODE_ENV=analyticsToolkit -v /root/nomad-coe:/certs:ro -v $PWD:/usr/src/app -w /usr/src/app -v /nomad/nomadlab/beaker-notebooks/user-data:/nomad/nomadlab/beaker-notebooks/user-data -d node:6 bash -c "npm install && npm start -- --image-type creedo webserver"

