apiVersion: "v1"
kind: "ReplicationController",
kind: Pod
  labels:
    user: "{{user}}"
    app: "{{imageType}}"
spec:
  containers:
  - image: "{{image}}"
    name: "{{imageType}}"
    ports:
    - containerPort: "{{port}}"
      name: "main-port"
      protocol: "TCP"
    imagePullPolicy: "IfNotPresent"
    volumeMounts:
    - mountPath: "/raw-data"
      name: "raw-data-volume"
      readOnly: true
    - mountPath: "/parsed"
      name: "parsed-data-volume"
      readOnly: true
    - mountPath: "/normalized"
      name: "normalized-data-volume"
      readOnly: true
    - mountPath: "{{homePath}}/notebooks"
      name: notebooks-data-volume
      readOnly: true
    - mountPath: "/data/private/{{user}}"
      name: "private-data-volume"
    - mountPath: "/data/shared"
      name: "shared-data-volume"
      readOnly: true
    - mountPath: "/data/shared/{{user}}"
      name: "my-shared-data-volume"
  volumes:
  - name: "parsed-data-volume"
    hostPath: { "path": "/nomad/nomadlab/parsed" }
  - name: "raw-data-volume"
    hostPath: { "path": "/nomad/nomadlab/raw-data"}
  - name: "normalized-data-volume"
    hostPath: { "path": "/nomad/nomadlab/normalized" }
  - name: "notebooks-data-volume"
    hostPath: { "path": "/nomad/nomadlab/beaker-notebooks/notebooks" }
  - name: "private-data-volume"
    hostPath: { "path": "{{userDataHostPath}}/private/{{user}}" }
  - name: "shared-data-volume"
    hostPath: { "path": "{{userDataHostPath}}/shared" }
  - name: "my-shared-data-volume"
    hostPath: { "path": "{{userDataHostPath}}/shared/{{user}}" }
