apiVersion: v1
kind: PersistentVolume
metadata:
    name: prometheus-server
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /nomad/nomadlab/servers/labdev-nomad/prometheus/server-volume
    type: Directory
