apiVersion: v1
kind: PersistentVolume
metadata:
    name: redis-user-db-volume
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /nomad/nomadlab/servers/labtest-nomad/prometheus/server-volume
    type: Directory
