---
apiVersion: "v1"
kind: Pod
metadata:
  name: "{{e podName}}"
  labels:
    user: "{{e user}}"
    image-type: "{{e imageType}}"
    image-subtype: "{{e imageSubtype}}"
    replacements-checksum: "{{e replacementsChecksum}}"
spec:
  imagePullSecrets:
  - name: garching-kube
  restartPolicy: Never
  containers:
  - image: "{{e image}}"
    name: "{{e imageType}}"
    command: ["start-notebook.sh"]
    args: ["--NotebookApp.token=\"\"",  "--NotebookApp.base_url=/jupyter", "--NotebookApp.allow_origin=*", "--NotebookApp.notebook_dir=/data/private/"]
    ports:
    - containerPort: {{n port}}
      name: "main-port"
      protocol: "TCP"
    imagePullPolicy: "IfNotPresent"
    volumeMounts:
    - mountPath: "/raw-data"
      name: "raw-data-volume"
      readOnly: true
    - mountPath: "/parsed"
      name: "parsed-data-volume"
      readOnly: true
    - mountPath: "/normalized"
      name: "normalized-data-volume"
      readOnly: true
    - mountPath: "/data/private"
      name: "private-data-volume"
    - mountPath: "/data/shared"
      name: "shared-data-volume"
      readOnly: true
    - mountPath: "/data/private/myshared"
      name: "my-shared-data-volume"
    readinessProbe:
      httpGet:
        path: "{{e healthPath}}"
        port: {{n port}}
      initialDelaySeconds: {{n healthDelay}}
      periodSeconds: {{n healthPeriod}}
    livenessProbe:
      httpGet:
        path: "{{e livePath}}"
        port: {{n port}}
      initialDelaySeconds: {{n liveDelay}}
      periodSeconds: {{n livePeriod}}
  volumes:
  - name: "parsed-data-volume"
    hostPath: { "path": "{{e nomadRoot}}/parsed" }
  - name: "raw-data-volume"
    hostPath: { "path": "{{e nomadRoot}}/raw-data"}
  - name: "normalized-data-volume"
    hostPath: { "path": "{{e nomadRoot}}/normalized" }
  - name: "private-data-volume"
    hostPath: { "path": "{{e nomadRoot}}/user-data/private/{{e user}}" }
  - name: "shared-data-volume"
    hostPath: { "path": "{{e nomadRoot}}/user-data/shared" }
  - name: "my-shared-data-volume"
    hostPath: { "path": "{{e nomadRoot}}/user-data/shared/{{e user}}" }
